version = 5.6.0
archive_dir = /etc/letsencrypt/archive/myporjecttaskflow.duckdns.org
cert = /etc/letsencrypt/live/myporjecttaskflow.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/myporjecttaskflow.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/myporjecttaskflow.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/myporjecttaskflow.duckdns.org/fullchain.pem
[renewalparams]
account = 0164a0118831a70aa309ba5c69b51a7d
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
myporjecttaskflow.duckdns.org = /var/www/certbot
